name: 'Django Test Action'
description: 'Runs Django tests'
inputs:
  python-version:
    description: 'Version of Python to use'
    required: true
    default: '3.8'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Run tests
      run: |
        python manage.py test --keepdb
      shell: bash