# Generated by Django 4.1.2 on 2023-10-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='desciption',
            new_name='description',
        ),
    ]
