name: Django application test with Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python manage.py test --keepdb
      env:
        TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
        TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
        TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
        DB_HOST: ${{ secrets.DB_HOST }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}