name: Django application test with Github Actions 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
    - name: Run tests
      run: |
        python manage.py test --keepdb
      env:
        TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
        TEST_DB_USER: kmwgqoxngbjjsi
        TEST_DB_PASSWORD: 7050a16b1d1959f9c86e657eecd65dec074fc761ae43ba11d98058ae2ab27c5a
        TEST_DB_HOST: ec2-34-228-248-175.compute-1.amazonaws.com
        SECRET_KEY: 6ps8j!crjgrxt34cqbqn7x&b3y%(fny8k8nh21+qa)%ws3fh!q
        EMAIL_HOST_PASSWORD: zqzgqhtxnrzudniz
        EMAIL_HOST_USER: utilityserviceemail@gmail.com
        PORT: 5432